---
title: "RADIANCE II - Payment Listing (Source: EDC Visit Details)"
#author: "HMB"
#date: "9/03/2020"
#last update: "9/16/2020"
#symbolic link to EDC data added
#cleanup added

output: html_document
---

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("logo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Details

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(readxl)
library(writexl)
library(sas7bdat)
library(tidyverse)
library(sqldf)
library(knitr)
library(kableExtra)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(haven)

rd_f_rand <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_rand.sas7bdat", NULL)
rd_f_visitdetails_screening <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_screening.sas7bdat", NULL)
rd_f_visitdetails_procedure <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_procedure.sas7bdat", NULL)
rd_f_visitdetails_preprocedure <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_preprocedure.sas7bdat", NULL)
rd_f_visitdetails_predischarge <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_predischarge.sas7bdat", NULL)
rd_f_visitdetails_p2 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_p2.sas7bdat", NULL)
rd_f_visitdetails_followupsv3_ <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followupsv3_.sas7bdat", NULL)
rd_f_visitdetails_followups2 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followups2.sas7bdat", NULL)
rd_f_visitdetails_followups_v8 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followups_v8.sas7bdat", NULL)
rd_f_visitdetails_followups_v6 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followups_v6.sas7bdat", NULL)
rd_f_visitdetails_followups_v1 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followups_v1.sas7bdat", NULL)
rd_f_visitdetails_followups <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followups.sas7bdat", NULL)
rd_f_visitdetails_followup_tpv <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_tpv.sas7bdat", NULL)
rd_f_visitdetails_followup_8 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_8.sas7bdat", NULL)
rd_f_visitdetails_followup_6 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_6.sas7bdat", NULL)
rd_f_visitdetails_followup_5 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_5.sas7bdat", NULL)
rd_f_visitdetails_followup_3 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_3.sas7bdat", NULL)
rd_f_visitdetails_followup_1 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_followup_1.sas7bdat", NULL)
rd_f_visitdetails_final <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_final.sas7bdat", NULL)
rd_f_visitdetails_discharged2 <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_discharged2.sas7bdat", NULL)
rd_f_visitdetails_cobaseline <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_cobaseline.sas7bdat", NULL)
rd_f_visitdetails_baseline <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_f_visitdetails_baseline.sas7bdat", NULL)
rd_payments <- read_sas("./data/raw_data/RADIANCEII_RDE-SASD/rd_payments.sas7bdat", NULL)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
vd_view_payments_all <- sqldf("
select 
rd_f_visitdetails_screening.sitename,
rd_f_visitdetails_screening.subjectnumberstr,
rd_f_visitdetails_screening.dov,
rd_f_visitdetails_screening.visitmnemonic,
rd_f_visitdetails_screening.i_date_payment_dts,
rd_f_visitdetails_screening.i_paymentamt,
rd_f_visitdetails_screening.i_currency,
rd_f_visitdetails_screening.i_paymentinvoice,
rd_f_visitdetails_screening.i_paymentmemo
from 
rd_f_visitdetails_screening
union
select 
rd_f_visitdetails_procedure.sitename,
rd_f_visitdetails_procedure.subjectnumberstr,
rd_f_visitdetails_procedure.dov,
rd_f_visitdetails_procedure.visitmnemonic,
rd_f_visitdetails_procedure.i_date_payment_dts,
rd_f_visitdetails_procedure.i_paymentamt,
rd_f_visitdetails_procedure.i_currency,
rd_f_visitdetails_procedure.i_paymentinvoice,
rd_f_visitdetails_procedure.i_paymentmemo
from 
rd_f_visitdetails_procedure
union
select 
rd_f_visitdetails_preprocedure.sitename,
rd_f_visitdetails_preprocedure.subjectnumberstr,
rd_f_visitdetails_preprocedure.dov,
rd_f_visitdetails_preprocedure.visitmnemonic,
rd_f_visitdetails_preprocedure.i_date_payment_dts,
rd_f_visitdetails_preprocedure.i_paymentamt,
rd_f_visitdetails_preprocedure.i_currency,
rd_f_visitdetails_preprocedure.i_paymentinvoice,
rd_f_visitdetails_preprocedure.i_paymentmemo
from 
rd_f_visitdetails_preprocedure
union
select 
rd_f_visitdetails_predischarge.sitename,
rd_f_visitdetails_predischarge.subjectnumberstr,
rd_f_visitdetails_predischarge.dov,
rd_f_visitdetails_predischarge.visitmnemonic,
rd_f_visitdetails_predischarge.i_date_payment_dts,
rd_f_visitdetails_predischarge.i_paymentamt,
rd_f_visitdetails_predischarge.i_currency,
rd_f_visitdetails_predischarge.i_paymentinvoice,
rd_f_visitdetails_predischarge.i_paymentmemo
from 
rd_f_visitdetails_predischarge
union
select 
rd_f_visitdetails_baseline.sitename,
rd_f_visitdetails_baseline.subjectnumberstr,
rd_f_visitdetails_baseline.dov,
rd_f_visitdetails_baseline.visitmnemonic,
rd_f_visitdetails_baseline.i_date_payment_dts,
rd_f_visitdetails_baseline.i_paymentamt,
rd_f_visitdetails_baseline.i_currency,
rd_f_visitdetails_baseline.i_paymentinvoice,
rd_f_visitdetails_baseline.i_paymentmemo
from 
rd_f_visitdetails_baseline
union
select 
rd_f_visitdetails_followup_1.sitename,
rd_f_visitdetails_followup_1.subjectnumberstr,
rd_f_visitdetails_followup_1.dov,
rd_f_visitdetails_followup_1.visitmnemonic,
rd_f_visitdetails_followup_1.i_date_payment_dts,
rd_f_visitdetails_followup_1.i_paymentamt,
rd_f_visitdetails_followup_1.i_currency,
rd_f_visitdetails_followup_1.i_paymentinvoice,
rd_f_visitdetails_followup_1.i_paymentmemo
from 
rd_f_visitdetails_followup_1
union
select 
rd_f_visitdetails_followup_3.sitename,
rd_f_visitdetails_followup_3.subjectnumberstr,
rd_f_visitdetails_followup_3.dov,
rd_f_visitdetails_followup_3.visitmnemonic,
rd_f_visitdetails_followup_3.i_date_payment_dts,
rd_f_visitdetails_followup_3.i_paymentamt,
rd_f_visitdetails_followup_3.i_currency,
rd_f_visitdetails_followup_3.i_paymentinvoice,
rd_f_visitdetails_followup_3.i_paymentmemo
from 
rd_f_visitdetails_followup_3
union
select 
rd_f_visitdetails_followup_5.sitename,
rd_f_visitdetails_followup_5.subjectnumberstr,
rd_f_visitdetails_followup_5.dov,
rd_f_visitdetails_followup_5.visitmnemonic,
rd_f_visitdetails_followup_5.i_date_payment_dts,
rd_f_visitdetails_followup_5.i_paymentamt,
rd_f_visitdetails_followup_5.i_currency,
rd_f_visitdetails_followup_5.i_paymentinvoice,
rd_f_visitdetails_followup_5.i_paymentmemo
from 
rd_f_visitdetails_followup_5
union
select 
rd_f_visitdetails_followup_6.sitename,
rd_f_visitdetails_followup_6.subjectnumberstr,
rd_f_visitdetails_followup_6.dov,
rd_f_visitdetails_followup_6.visitmnemonic,
rd_f_visitdetails_followup_6.i_date_payment_dts,
rd_f_visitdetails_followup_6.i_paymentamt,
rd_f_visitdetails_followup_6.i_currency,
rd_f_visitdetails_followup_6.i_paymentinvoice,
rd_f_visitdetails_followup_6.i_paymentmemo
from 
rd_f_visitdetails_followup_6
union
select 
rd_f_visitdetails_followup_8.sitename,
rd_f_visitdetails_followup_8.subjectnumberstr,
rd_f_visitdetails_followup_8.dov,
rd_f_visitdetails_followup_8.visitmnemonic,
rd_f_visitdetails_followup_8.i_date_payment_dts,
rd_f_visitdetails_followup_8.i_paymentamt,
rd_f_visitdetails_followup_8.i_currency,
rd_f_visitdetails_followup_8.i_paymentinvoice,
rd_f_visitdetails_followup_8.i_paymentmemo
from 
rd_f_visitdetails_followup_8
union
select 
rd_f_visitdetails_cobaseline.sitename,
rd_f_visitdetails_cobaseline.subjectnumberstr,
rd_f_visitdetails_cobaseline.dov,
rd_f_visitdetails_cobaseline.visitmnemonic,
rd_f_visitdetails_cobaseline.i_date_payment_dts,
rd_f_visitdetails_cobaseline.i_paymentamt,
rd_f_visitdetails_cobaseline.i_currency,
rd_f_visitdetails_cobaseline.i_paymentinvoice,
rd_f_visitdetails_cobaseline.i_paymentmemo
from 
rd_f_visitdetails_cobaseline
union
select 
rd_f_visitdetails_discharged2.sitename,
rd_f_visitdetails_discharged2.subjectnumberstr,
rd_f_visitdetails_discharged2.dov,
rd_f_visitdetails_discharged2.visitmnemonic,
rd_f_visitdetails_discharged2.i_date_payment_dts,
rd_f_visitdetails_discharged2.i_paymentamt,
rd_f_visitdetails_discharged2.i_currency,
rd_f_visitdetails_discharged2.i_paymentinvoice,
rd_f_visitdetails_discharged2.i_paymentmemo
from 
rd_f_visitdetails_discharged2
union
select 
rd_f_visitdetails_final.sitename,
rd_f_visitdetails_final.subjectnumberstr,
rd_f_visitdetails_final.dov,
rd_f_visitdetails_final.visitmnemonic,
rd_f_visitdetails_final.i_date_payment_dts,
rd_f_visitdetails_final.i_paymentamt,
rd_f_visitdetails_final.i_currency,
rd_f_visitdetails_final.i_paymentinvoice,
rd_f_visitdetails_final.i_paymentmemo
from 
rd_f_visitdetails_final
union
select 
rd_f_visitdetails_p2.sitename,
rd_f_visitdetails_p2.subjectnumberstr,
rd_f_visitdetails_p2.dov,
rd_f_visitdetails_p2.visitmnemonic,
rd_f_visitdetails_p2.i_date_payment_dts,
rd_f_visitdetails_p2.i_paymentamt,
rd_f_visitdetails_p2.i_currency,
rd_f_visitdetails_p2.i_paymentinvoice,
rd_f_visitdetails_p2.i_paymentmemo
from 
rd_f_visitdetails_p2
union
select 
rd_f_visitdetails_followup_tpv.sitename,
rd_f_visitdetails_followup_tpv.subjectnumberstr,
rd_f_visitdetails_followup_tpv.dov,
rd_f_visitdetails_followup_tpv.visitmnemonic,
rd_f_visitdetails_followup_tpv.i_date_payment_dts,
rd_f_visitdetails_followup_tpv.i_paymentamt,
rd_f_visitdetails_followup_tpv.i_currency,
rd_f_visitdetails_followup_tpv.i_paymentinvoice,
rd_f_visitdetails_followup_tpv.i_paymentmemo
from 
rd_f_visitdetails_followup_tpv
union
select 
rd_f_visitdetails_followups.sitename,
rd_f_visitdetails_followups.subjectnumberstr,
rd_f_visitdetails_followups.dov,
rd_f_visitdetails_followups.visitmnemonic,
rd_f_visitdetails_followups.i_date_payment_dts,
rd_f_visitdetails_followups.i_paymentamt,
rd_f_visitdetails_followups.i_currency,
rd_f_visitdetails_followups.i_paymentinvoice,
rd_f_visitdetails_followups.i_paymentmemo
from 
rd_f_visitdetails_followups
union
select 
rd_f_visitdetails_followups_v1.sitename,
rd_f_visitdetails_followups_v1.subjectnumberstr,
rd_f_visitdetails_followups_v1.dov,
rd_f_visitdetails_followups_v1.visitmnemonic,
rd_f_visitdetails_followups_v1.i_date_payment_dts,
rd_f_visitdetails_followups_v1.i_paymentamt,
rd_f_visitdetails_followups_v1.i_currency,
rd_f_visitdetails_followups_v1.i_paymentinvoice,
rd_f_visitdetails_followups_v1.i_paymentmemo
from 
rd_f_visitdetails_followups_v1
union
select 
rd_f_visitdetails_followups_v6.sitename,
rd_f_visitdetails_followups_v6.subjectnumberstr,
rd_f_visitdetails_followups_v6.dov,
rd_f_visitdetails_followups_v6.visitmnemonic,
rd_f_visitdetails_followups_v6.i_date_payment_dts,
rd_f_visitdetails_followups_v6.i_paymentamt,
rd_f_visitdetails_followups_v6.i_currency,
rd_f_visitdetails_followups_v6.i_paymentinvoice,
rd_f_visitdetails_followups_v6.i_paymentmemo
from 
rd_f_visitdetails_followups_v6
union
select 
rd_f_visitdetails_followups_v8.sitename,
rd_f_visitdetails_followups_v8.subjectnumberstr,
rd_f_visitdetails_followups_v8.dov,
rd_f_visitdetails_followups_v8.visitmnemonic,
rd_f_visitdetails_followups_v8.i_date_payment_dts,
rd_f_visitdetails_followups_v8.i_paymentamt,
rd_f_visitdetails_followups_v8.i_currency,
rd_f_visitdetails_followups_v8.i_paymentinvoice,
rd_f_visitdetails_followups_v8.i_paymentmemo
from 
rd_f_visitdetails_followups_v8
union
select 
rd_f_visitdetails_followups2.sitename,
rd_f_visitdetails_followups2.subjectnumberstr,
rd_f_visitdetails_followups2.dov,
rd_f_visitdetails_followups2.visitmnemonic,
rd_f_visitdetails_followups2.i_date_payment_dts,
rd_f_visitdetails_followups2.i_paymentamt,
rd_f_visitdetails_followups2.i_currency,
rd_f_visitdetails_followups2.i_paymentinvoice,
rd_f_visitdetails_followups2.i_paymentmemo
from 
rd_f_visitdetails_followups2
union
select 
rd_f_visitdetails_followupsv3_.sitename,
rd_f_visitdetails_followupsv3_.subjectnumberstr,
rd_f_visitdetails_followupsv3_.dov,
rd_f_visitdetails_followupsv3_.visitmnemonic,
rd_f_visitdetails_followupsv3_.i_date_payment_dts,
rd_f_visitdetails_followupsv3_.i_paymentamt,
rd_f_visitdetails_followupsv3_.i_currency,
rd_f_visitdetails_followupsv3_.i_paymentinvoice,
rd_f_visitdetails_followupsv3_.i_paymentmemo
from 
rd_f_visitdetails_followupsv3_
")
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(DT)

vd_view_payments_all %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
rm(list = ls())
gc()
```